project:
  type: website

website:
  title: "Group 10"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: The Team
    left:
      - href: about.qmd
        text: Overview
      - href: methods.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: conclusion.qmd
        text: Conclusions

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

